### ISSUE TITLE
esx dialog box

### ISSUE THREAD

**Issue by keeeeeeey** [Musiker15/weaponammo#1]
Hi i wanted to make a  esx dialog box and chose the amount of ammo that you wanted to put in your weapon is it possibile and if yes how?

**Comment by Musiker15** [comment]
I am working on an update where you have an item that you can only use for a pistol, an item that you can only use for an smg, ...

**Comment by anes66** [comment]
> Yes that's correct. Next update will come by the end of this week at the latest.

thx buddy will definitly wait for it :D

**Comment by Musiker15** [comment]
Update v4.0 is released :)

https://github.com/Musiker15/weaponammo/releases
