### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by anes66** [Musiker15/weaponammo#2]
is it possible that you can add male weapons like knife and other stuff and is it possible to add in the config Custom weapons

you can see here what i mean

https://forum.cfx.re/t/tool-vweaponstoolkit-create-addon-weapons-with-ease/4733757

i hope you understand what i mean :)

**Comment by Musiker15** [comment]
I can have a look at this but I don't know if I implement this.

**Comment by anes66** [comment]
> I can have a look at this but I don't know if I implement this.

the thing is you can create weapons with addon name like weapon_glock or  weapon_kar98

and then to add like ammo i must see how i can make it :D
