### ISSUE TITLE
isThrowable

### ISSUE THREAD

**Issue by Gill0** [Musiker15/weaponammo#3]
Little Misstake :)

function isThrowable() 
	local playerPed = PlayerPedId()
	for _,Throwable in pairs(Config.Weapons.Flares) do <<<--------
		if (Throwable.weaponHash == GetSelectedPedWeapon(playerPed)) then 
			return true
		end
	end
	return false
end

to

function isThrowable() 
	local playerPed = PlayerPedId()
	for _,Throwable in pairs(Config.Weapons.Throwables) do <<<---------
		if (Throwable.weaponHash == GetSelectedPedWeapon(playerPed)) then
			return true
		end
	end
	return false
end

**Comment by Musiker15** [comment]
Yes, you are right. :)
